name: Increment Version on PR or Commit

on:
  pull_request:
    types:
      - closed
  push:
    branches:
      - main

jobs:
  increment-version:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: "increment-pubspec-version"
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Run Increment Pubspec Version
        uses: ./
        with:
          enable_on_commit: "true"
          github_token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Create Tag with New Version
        if: steps.increment_version.outputs.new_version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag v${{ steps.increment_version.outputs.new_version }}
          git push origin v${{ steps.increment_version.outputs.new_version }}
